### PR TITLE
Rename "enter" named range to "entry" to conform to the latest spec

### PR DESCRIPTION
**Pull request by dream-ellie**
**TL;DR**
Update "enter" to "entry" to bring polyfill closer to the latest spec

**Details**
According to this comment, "enter" was renamed to "entry" so this PR updates the polyfill accordingly.

### CODE REVIEW

**Comment by kevers-google** [comment]
Please run "npm run dev" to rebuild the binaries.  These should be part of the pull request.

**Comment by dream-ellie** [comment]
> Please run "npm run dev" to rebuild the binaries. These should be part of the pull request.

@kevers-google done

**Comment by kevers-google** [comment]
Merged PR#108, which has created a merge conflict for the binaries.  You'll need to merge master and rebuild the binaries so that the id Fix in #108 is reflected in the updated binaries for this PR.  When resolving the merge conflict it might be simplest to stomp your local changed with the version in master and then rebuild to create fresh local binaries.

**Comment by flackr** [comment]
> Please run "npm run dev" to rebuild the binaries. These should be part of the pull request.

I just finished automating this step in an action script so the repo no longer needs the `dist` folder.

**Comment by kevers-google** [comment]
The dist directory has been removed from the build, as the build/deploy has been automated.  Kindly cleanup to remove updating the dist files, and we should be good to go.

**Pull request merged**
