### PR TITLE
Fix playState getter

### PR DESCRIPTION
**Pull request by kevers-google**
Tiny patch to fix the scope of the details variable in the playState getter. Tests were able to pass even without marking details with const/let/var, since the assignment could default to the global scope.  In a strict environment this is not allowed.

### CODE REVIEW

**Review by flackr — COMMENTED** [review]
Doesn't this require rebuilding the release?

**Comment by kevers-google** [comment]
Ack.  I'll put together a new pull request.

**Comment by flackr** [comment]
GitHub is saying there are merge conflicts, perhaps you need to sync your local branch to master and rebuild.

**Comment by kevers-google** [comment]
Would like to abandon this pull request.  Have a new one with the conflicts resolved.

**Pull request closed without merging**
